CREATE DATABASE LIKE_SISTEMAS;
USE LIKE_SISTEMAS;

/*------TABELA DE SUBCATEGORIAS------*/
CREATE TABLE subCategoria (
ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, 
NOME VARCHAR(50) NOT NULL);

SELECT * FROM subCategoria;


/*------TABELA DE PRODUTOS------*/
CREATE TABLE produto (
ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, 
NOME VARCHAR(50) NOT NULL,
VALOR DECIMAL(8,2) NOT NULL,
SUBCATEGORIA INTEGER NOT NULL);

ALTER TABLE produto ADD CONSTRAINT FK_PRODUTO_SUBCATEGORIA FOREIGN KEY (SUBCATEGORIA) REFERENCES subCategoria (ID);

SELECT produto.ID,produto.NOME,SUBCATEGORIA.NOME as SUBCATEGORIA FROM produto INNER JOIN subCategoria ON produto.SUBCATEGORIA = subcategoria.ID; 


/*------TABELA DE PRODUTOS ORÇAMENTO------*/
CREATE TABLE produtosOrcamento(
PRODUTO INTEGER NOT NULL ,
ORCAMENTO INTEGER NOT NULL,
QUANTIDADE INTEGER NOT NULL
);

ALTER TABLE produtosOrcamento ADD CONSTRAINT FK_ORCAMENTO_CLIENTE FOREIGN KEY (ORCAMENTO) REFERENCES orcamento (ID);
ALTER TABLE produtosOrcamento ADD CONSTRAINT FK_ORCAMENTO_PRODUTO FOREIGN KEY (PRODUTO) REFERENCES produto (ID);


SELECT produtosOrcamento.QUANTIDADE,produto.NOME,orcamento.NOME_CLIENTE FROM produtosOrcamento 
INNER JOIN produto ON produtosOrcamento.PRODUTO = produto.ID
INNER JOIN orcamento ON produtosOrcamento.ORCAMENTO = orcamento.ID;


/*------TABELA DE ORÇAMENTOS------*/
CREATE TABLE orcamento (
ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME_CLIENTE VARCHAR(45) NOT NULL,
DATA_CRIACAO DATE NOT NULL
);

SELECT * FROM orcamento;





